mongo integration completed
anchovycation/pingu-api pull request #60
Opened 2022-09-05 18:30 UTC by beyzaerkan

Close #59

2022-09-05 18:32 UTC, beyzaerkan commented
Kod mantıksal anlamda doğru görünüyor fakat ilginç bir şekilde bazen izleme sayfasında istenen şeyler yapılamıyor. İlgili olaya ait hata fırlatılıyor. Sende de aynısı olacak mı diye dener misin? @saracalihan

2022-09-07 18:06 UTC, saracalihan requested changes

2022-09-07 18:06 UTC, saracalihan commented on src/Database.js
> +  await Mongoose.connect(process.env.MONGO_HOST + "/pingu",
burada host kullanmak yerine doğrudan tüm connection string'i dışarıdan almak daha mantıklı olur çünkü benim hostum dışında user, db bilgilerim vs. de olabilir.

2022-09-12 18:01 UTC, saracalihan approved these changes
@beyzaerkan  Eline sağlık, oldukça uzun ve tatlı bir iş oldu 🤗 🍾

2022-09-12 18:01 UTC, merged